" syntax on
source ~/.vimrc
source ~/.vim/highlight_gui.vim

set columns=140
set lines=140

set guioptions=c  " see guipotions http://vimwiki.net/?%27guioptions%27
set guifont=Ricty\ Diminished\ Regular:h13
" set guitablabel=>%t\ %m

set ambiwidth=double
set noimdisable

set transparency=10
" autocmd FocusGained * set background
" autocmd FocusLost * set background
 
noremap <C-Tab> :tabnext<CR>
noremap <C-S-Tab> :tabprevious<CR>

