" syntax on
source ~/.vimrc
source ~/.vim/highlight_gui.vim

set columns=160
set lines=140

set guioptions=c  " see guipotions http://vimwiki.net/?%27guioptions%27
set guifontwide=HackGen\ Regular:h12
" set guifont=Ricty\ Diminished\ Regular:h13
set guifont=x14y24pxHeadUpDaisy:h13
" set guitablabel=>%t\ %m

set ambiwidth=double
" set noimdisable

set transparency=10
" autocmd FocusGained * set background
" autocmd FocusLost * set background
 
noremap <C-Tab> :tabnext<CR>
noremap <C-S-Tab> :tabprevious<CR>

