# ARCH
ARCH=`arch`
BREW_DIR=".homebrew_$ARCH"
BREW_DIR_CACHE=".homebrew_$ARCH""_cache"
# export PYENV_ROOT="$HOME/.pyenv_$ARCH"
export ANYENV_ROOT="$HOME/.anyenv_$ARCH"

export LSCOLORS=gxfxcxdxbxegedabagacec
export LANG=ja_JP.UTF-8
export LC_CTYPE=ja_JP.UTF-8
export LC_TIME=en_US.UTF-8
# export PERL_CPANM_OPT="--mirror ftp://ftp.yz.yamagata-u.ac.jp/pub/lang/cpan/"
export GAE_PATH=$HOME/$BREW_DIR/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/platform/google_appengine

# for Mac OS X
case ${OSTYPE} in darwin*)
	export HOMEBREW=~/$BREW_DIR
	export HOMEBREW_CACHE=~/$BREW_DIR_CACHE
	export MANPATH=$MANPATH:$HOMEBREW/share/man
	export HOMEBREW_CELLAR=$HOMEBREW/Cellar
	export HOMEBREW_PREFIX=$HOMEBREW
	export HOMEBREW_REPOSITORY=$HOMEBREW
	export HOMEBREW_CASK_OPTS="--appdir=$HOME/Applications"

	path=($HOME/.rbenv/shims $HOMEBREW/share/npm/bin $HOME/.bin $HOMEBREW/opt/openjdk\@11/bin $HOMEBREW/sbin $HOMEBREW/bin $HOME/.nodebrew/current/bin /usr/local/bin $path)
	# path=($PYENV_ROOT/bin $path)
	# homebrew
	fpath=($HOMEBREW/share/zsh/site-functions $HOMEBREW/share/zsh-completions $HOMEBREW/share/zsh/functions $fpath)

	unalias run-help
	autoload run-help
	HELPDIR=$HOMEBREW/share/zsh/help
esac

typeset -U path cdpath fpath manpath

HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000

ps

# eval "$(pyenv init --path)"

# Added by `nodenv init` on Tue Nov  4 01:01:59 JST 2025
eval "$(nodenv init - --no-rehash zsh)"
