export LSCOLORS=gxfxcxdxbxegedabagacec
export LANG=ja_JP.UTF-8
export LC_CTYPE=ja_JP.UTF-8
export LC_TIME=en_US.UTF-8
# export PERL_CPANM_OPT="--mirror ftp://ftp.yz.yamagata-u.ac.jp/pub/lang/cpan/"
export GAE_PATH=$HOME/.homebrew/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/platform/google_appengine

# for Mac OS X
case ${OSTYPE} in darwin*)
	export HOMEBREW=~/.homebrew
	export HOMEBREW_CACHE=~/.homebrew_cache
	export MANPATH=$MANPATH:$HOMEBREW/share/man
	export HOMEBREW_CELLAR=$HOMEBREW/Cellar
	export HOMEBREW_PREFIX=$HOMEBREW
	export HOMEBREW_REPOSITORY=$HOMEBREW
	export HOMEBREW_CASK_OPTS="--appdir=$HOME/Applications"

	path=($PYENV_ROOT/bin $HOME/.rbenv/shims $HOME/.homebrew/share/npm/bin $HOME/.bin $HOMEBREW/opt/openjdk\@11/bin $HOMEBREW/sbin $HOMEBREW/bin /usr/local/bin $path)
	# homebrew
	fpath=($HOMEBREW/share/zsh/site-functions $HOMEBREW/share/zsh-completions $HOMEBREW/share/zsh/functions $fpath)

	unalias run-help
	autoload run-help
	HELPDIR=$HOMEBREW/share/zsh/help
esac

typeset -U path cdpath fpath manpath

HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000

ps

export PYENV_ROOT="$HOME/.pyenv"
eval "$(pyenv init --path)"

#if [ -e ~/share/01_Private ]; then 
#	echo -e $'\e[1m already mounted ~/share\e[m'
#else
#	ping -t 2 -c 1 192.168.2.30 >> /dev/null
#	RET=$?
#	if [ ${RET} -eq "0" ]; then
#		if [ -e ~/share ]; then 
#			mount_afp afp://xy4br3:xy4br3@192.168.2.30/share ~/share/
#		else 
#			mkdir ~/share
#			mount_afp afp://xy4br3:xy4br3@192.168.2.30/share ~/share/
#		fi
#		echo -e $'\e[1m mount ~/share \e[m'
#	else
#		echo -e $'\e[1m not connected xy4brNetwork\e[m'
#	fi
#fi
#
